adapt_names_cow<-function(col){
  col<-gsub("AAB","Antigua & Barbuda", col)
  col<-gsub("AFG","Afghanistan", col)
  col<-gsub("ALB","Albania", col)
  col<-gsub("ALG","Algeria", col)
  col<-gsub("AND","Andorra", col)
  col<-gsub("ANG","Angola", col)
  col<-gsub("ARG","Argentina", col)
  col<-gsub("ARM","Armenia", col)
  col<-gsub("AUL","Australia", col)
  col<-gsub("AUS","Austria", col)
  col<-gsub("AUH","Austria", col)
  col<-gsub("AZE ","Azerbaijan", col)
  col<-gsub("BAH","Bahrain", col)
  col<-gsub("BAR","Barbados", col)
  col<-gsub("BEL","Belgium", col)
  col<-gsub("BEN","Benin", col)
  col<-gsub("BFO","Burkina Faso", col)
  col<-gsub("BHM ","Bahamas", col)
  col<-gsub("BHU","Bhutan", col)
  col<-gsub("BLR","Belarus", col)
  col<-gsub("BLZ","Belize", col)
  col<-gsub("BNG ","Bangladesh", col)
  col<-gsub("BOL","Bolivia", col)
  col<-gsub("BOS","Bosnia-Herzegovina", col)
  col<-gsub("BOT","Botswana", col)
  col<-gsub("BRA","Brazil", col)
  col<-gsub("BRU","Brunei", col)
  col<-gsub("BUI","Burundi", col)
  col<-gsub("BUL","Bulgaria", col)
  col<-gsub("CAM","Cambodia", col)
  col<-gsub("CAN","Canada", col)
  col<-gsub("CAO","Cameroon", col)
  col<-gsub("CAP","Cape Verde", col)
  col<-gsub("CDI","Ivory Coast", col)
  col<-gsub("CEN ","Central African Republic", col)
  col<-gsub("CHA","Chad", col)
  col<-gsub("CHL","Chile", col)
  col<-gsub("CHN","China", col)
  col<-gsub("COL","Colombia", col)
  col<-gsub("COM","Comoros", col)
  col<-gsub("CON","Congo", col)
  col<-gsub("COS","Costa Rica", col)
  col<-gsub("CRO","Croatia", col)
  col<-gsub("CUB","Cuba", col)
  col<-gsub("CYP","Cyprus", col)
  col<-gsub("CZR","Czech Republic", col)
  col<-gsub("CZE","Czechoslovakia", col)
  col<-gsub("DEN","Denmark", col)
  col<-gsub("DJI","Djibouti", col)
  col<-gsub("DMA","Dominica", col)
  col<-gsub("DOM","Dominican Republic", col)
  # col<-gsub("DRC ","Democratic Republic of the Congo", col)
  col<-gsub("ECU","Ecuador", col)
  col<-gsub("EGY","Egypt", col)
  col<-gsub("EQG","Equatorial Guine", col)
  col<-gsub("ERI","Eritrea", col)
  col<-gsub("EST","Estonia", col)
  col<-gsub("ETH","Ethiopia", col)
  col<-gsub("FIJ","Fiji", col)
  col<-gsub("FIN","Finland", col)
  col<-gsub("FRN","France", col)
  col<-gsub("FSM","Federated States of Micronesia", col)
  col<-gsub("GAB","Gabon", col)
  col<-gsub("GAM","Gambia", col)
  col<-gsub("GHA","Ghana", col)
  col<-gsub("GMY","Germany", col)
  col<-gsub("GDR","East Germany", col)
  col<-gsub("GFR","West Germany", col)
  col<-gsub("GNB","Guin-Bissau", col)
  col<-gsub("GRC","Greece", col)
  col<-gsub("GRG","Georgia", col)
  col<-gsub("GRN","Grenada", col)
  col<-gsub("GUA","Guatemala", col)
  col<-gsub("GUI","Guinea", col)
  col<-gsub("GUY","Guyana", col)
  col<-gsub("HAI","Haiti", col)
  col<-gsub("HON","Honduras", col)
  col<-gsub("HUN","Hungary", col)
  col<-gsub("ICE","Iceland", col)
  col<-gsub("IND","India", col)
  col<-gsub("INS","Indonesia", col)
  col<-gsub("IRE","Ireland", col)
  col<-gsub("IRN","Iran", col)
  col<-gsub("IRQ","Iraq", col)
  col<-gsub("ISR","Israel", col)
  col<-gsub("ITA","Italy", col)
  col<-gsub("JAM","Jamaica", col)
  col<-gsub("JOR","Jordan", col)
  col<-gsub("JPN","Japan", col)
  col<-gsub("KEN","Kenya", col)
  col<-gsub("KIR","Kiribati", col)
  col<-gsub("KUW","Kuwait", col)
  col<-gsub("KYR","Kyrgyz Republic", col)
  col<-gsub("KZK","Kazakhstan", col)
  col<-gsub("LAO","Laos", col)
  col<-gsub("LAT","Latvia", col)
  col<-gsub("LBR","Liberia", col)
  col<-gsub("LEB","Lebanon", col)
  col<-gsub("LES","Lesotho", col)
  col<-gsub("LIB","Libya", col)
  col<-gsub("LIE","Liechtenstein", col)
  col<-gsub("LIT","Lithuania", col)
  col<-gsub("LUX","Luxembourg", col)
  col<-gsub("MAA","Mauritania", col)
  col<-gsub("MAC","Macedonia", col)
  col<-gsub("MAD","Maldive Islands", col)
  col<-gsub("MAG","Madagascar", col)
  col<-gsub("MAL","Malaysia", col)
  col<-gsub("MAS","Mauritius", col)
  col<-gsub("MAW","Malawi", col)
  col<-gsub("MEX","Mexico", col)
  col<-gsub("MLD","Moldova", col)
  col<-gsub("MLI","Mali", col)
  col<-gsub("MLT","Malta", col)
  col<-gsub("MNC","Monaco", col)
  col<-gsub("MON","Mongolia", col)
  col<-gsub("MOR","Morocco", col)
  col<-gsub("MSI","Marshall Islands", col)
  col<-gsub("MYA","Burma", col)
  col<-gsub("MZM","Mozambique", col)
  col<-gsub("NAM","Namibia", col)
  col<-gsub("NAU","Nauru", col)
  col<-gsub("NEP","Nepal", col)
  col<-gsub("NEW","New Zealand", col)
  col<-gsub("NIC","Nicaragua", col)
  col<-gsub("NIG","Nigeria", col)
  col<-gsub("NIR","Niger", col)
  col<-gsub("NOR","Norway", col)
  col<-gsub("NTH","Netherlands", col)
  col<-gsub("OMA","Oman", col)
  col<-gsub("PAK","Pakistan", col)
  col<-gsub("PAL","Palau", col)
  col<-gsub("PAN","Panama", col)
  col<-gsub("PAR","Paraguay", col)
  col<-gsub("PER","Peru", col)
  col<-gsub("PHI","Philippines", col)
  col<-gsub("PNG","Papua New Guin", col)
  col<-gsub("POL","Poland", col)
  col<-gsub("POR","Portugal", col)
  col<-gsub("PRK","North Korea", col)
  col<-gsub("QAT","Qatar", col)
  col<-gsub("ROK","South Korea", col)
  col<-gsub("ROM","Romania", col)
  col<-gsub("RUM","Romania", col)
  col<-gsub("RUS","Russia", col)
  col<-gsub("RWA","Rwanda", col)
  col<-gsub("SAF","South Africa", col)
  col<-gsub("SAL","El Salvador", col)
  col<-gsub("SAU","Saudi Arabia", col)
  col<-gsub("SEN","Senegal", col)
  col<-gsub("SEY","Seychelles", col)
  col<-gsub("SIE","Sierra Leone", col)
  col<-gsub("SIN","Singapore", col)
  col<-gsub("SKN","St. Kitts-Nevis", col)
  col<-gsub("SLO","Slovakia", col)
  col<-gsub("SLU","St. Lucia", col)
  col<-gsub("SLV","Slovenia", col)
  col<-gsub("SNM","San Marino", col)
  col<-gsub("SOL","Solomon Islands", col)
  col<-gsub("SOM","Somalia", col)
  col<-gsub("SPN","Spain", col)
  col<-gsub("SRI","Sri Lanka", col)
  col<-gsub("STP","Sao Tome-Principe", col)
  col<-gsub("SUD","Sudan", col)
  col<-gsub("SUR","Suriname", col)
  col<-gsub("SVG","St. Vincent and the Grenadines", col)
  col<-gsub("SWA","Swaziland", col)
  col<-gsub("SWD","Sweden", col)
  col<-gsub("SWZ","Switzerland", col)
  col<-gsub("SYR","Syria", col)
  col<-gsub("TAJ","Tajikistan", col)
  col<-gsub("TAW","Taiwan", col)
  col<-gsub("TAZ","Tanzania", col)
  col<-gsub("THI","Thailand", col)
  col<-gsub("TKM","Turkmenistan", col)
  col<-gsub("TOG","Togo", col)
  col<-gsub("TON","Tonga", col)
  col<-gsub("TRI","Trinidad-Tobago", col)
  col<-gsub("TUN","Tunisia", col)
  col<-gsub("TUR","Turkey", col)
  col<-gsub("TUV","Tuvalu", col)
  col<-gsub("UAE","UAE", col)
  col<-gsub("UGA","Uganda", col)
  col<-gsub("UKG","United Kingdom", col)
  col<-gsub("UKR","Ukraine", col)
  col<-gsub("URU","Uruguay", col)
  col<-gsub("USR","Russia", col)
  col<-gsub("USA","United States", col)
  col<-gsub("UZB","Uzbekistan", col)
  col<-gsub("VAN","Vanuatu", col)
  col<-gsub("VEN","Venezuela", col)
  col<-gsub("VTM","Vietnam", col)
  col<-gsub("WSM","Western Samoa", col)
  col<-gsub("YEM","Yemen", col)
  col<-gsub("YAR","NorthYemen", col)
  col<-gsub("YUG","Yugoslavia", col)
  col<-gsub("ZAM","Zambia", col)
  col<-gsub("ZIM","Zimbabwe", col)
  col<-gsub("ZAI","Zaire", col)
  col<-gsub("DRC","Zaire", col)
  return(col)
}




adapt_names_pol<-function(col){
  col<-gsub("Bosnia","Bosnia-Herzegovina", col)
  col<-gsub("Korea South","South Korea", col)
  col<-gsub("Korea North","North Korea", col)
  col<-gsub("Slovak Republic","Slovakia", col)
  col<-gsub("Trinidad and Tobago","Trinidad-Tobago", col)
  col<-gsub("Congo Kinshasa","Zaire", col)
  col<-gsub("Cote D'Ivoire","Ivory Coast", col)
  col<-gsub("USSR","Russia", col)
  col<-gsub("Germany East","East Germany", col)
  col<-gsub("Germany West","West Germany", col)
  col<-gsub("Serbia and Montenegro","Yugoslavia", col)
  col<-gsub("Serbia","Yugoslavia", col)
  return(col)
}





adapt_names_trade<-function(col){

#col<-gsub("","", col)
#trade$importer2<-gsub("","", trade$importer2)
col<-gsub("Democratic Republic of the Congo","Zaire", col)
col<-gsub("German Democratic Republic","East Germany", col)
col<-gsub("German Federal Republic","West Germany", col)
col<-gsub("United Arab Emirates","UAE", col)
col<-gsub("Trinidad and Tobago","Trinidad-Tobago", col)
col<-gsub("Bosnia and Herzegovina","Bosnia-Herzegovina", col)
col<-gsub("United States of America","United States", col)
col<-gsub("GermanFederalRepublic","West Germany", col)
col<-gsub("GermanDemocraticRepublic","East Germany", col)

return(col)}





adapt_names_iso<-function(col){

# col<-gsub("ATG","Antigua & Barbuda", col)
# col<-gsub("AFG","Afghanistan", col)
# col<-gsub("ALB","Albania", col)
col<-gsub("DZA","Algeria", col)
# col<-gsub("AND","Andorra", col)
col<-gsub("AGO","Angola", col)
col<-gsub("ARG","Argentina", col)
# col<-gsub("ARM","Armenia", col)
col<-gsub("AUS","Australia", col)
col<-gsub("AUT","Austria", col)
# col<-gsub("AZE ","Azerbaijan", col)
# col<-gsub("BHR","Bahrain", col)
# col<-gsub("BRB","Barbados", col)
col<-gsub("BEL","Belgium", col)
# col<-gsub("BEN","Benin", col)
# col<-gsub("BFA","Burkina Faso", col)
# col<-gsub("BHS ","Bahamas", col)
# col<-gsub("BTN","Bhutan", col)
# col<-gsub("BLR","Belarus", col)
# col<-gsub("BLZ","Belize", col)
# col<-gsub("BGD ","Bangladesh", col)
col<-gsub("BOL","Bolivia", col)
col<-gsub("BIH","Bosnia-Herzegovina", col)
# col<-gsub("BWA","Botswana", col)
col<-gsub("BRA","Brazil", col)
# col<-gsub("BRN","Brunei", col)
# col<-gsub("BDI","Burundi", col)
col<-gsub("BGR","Bulgaria", col)
# col<-gsub("KHM","Cambodia", col)
col<-gsub("CAN","Canada", col)
col<-gsub("CMR","Cameroon", col)
# col<-gsub("CPV","Cape Verde", col)
col<-gsub("CIV","Ivory Coast", col)
# col<-gsub("CAF ","Central African Republic", col)
# col<-gsub("TCD","Chad", col)
col<-gsub("CHL","Chile", col)
col<-gsub("CHN","China", col)
col<-gsub("COL","Colombia", col)
# col<-gsub("COM","Comoros", col)
# col<-gsub("COG","Congo", col)
col<-gsub("CRI","Costa Rica", col)
col<-gsub("HRV","Croatia", col)
col<-gsub("CUB","Cuba", col)
# col<-gsub("CYP","Cyprus", col)
col<-gsub("CZE","Czech Republic", col)
col<-gsub("CZE","Czechoslovakia", col)
col<-gsub("DNK","Denmark", col)
# col<-gsub("DJI","Djibouti", col)
# col<-gsub("DMA","Dominica", col)
# col<-gsub("DOM","Dominican Republic", col)
col<-gsub("ZAR","Zaire", col)
col<-gsub("ECU","Ecuador", col) 
col<-gsub("EGY","Egypt", col)
# col<-gsub("GNQ","Equatorial Guinea", col)
# col<-gsub("ERI","Eritrea", col)
# col<-gsub("EST","Estonia", col)
# col<-gsub("ETH","Ethiopia", col)
# col<-gsub("FJI","Fiji", col)
# col<-gsub("FIN","Finland", col)
col<-gsub("FRA","France", col)
# col<-gsub("FSM","Federated States of Micronesia", col)
# col<-gsub("GAB","Gabon", col)
# col<-gsub("GMB","Gambia", col)
col<-gsub("GHA","Ghana", col)
col<-gsub("DEU","Germany", col)
col<-gsub("GDR","East Germany", col)
col<-gsub("GFR","Germany", col)
# col<-gsub("GNB","Guinea-Bissau", col)
col<-gsub("GRC","Greece", col)
# col<-gsub("GEO","Georgia", col)
# col<-gsub("GRD","Grenada", col)
# col<-gsub("GTM","Guatemala", col)
# col<-gsub("GIN","Guinea", col)
# col<-gsub("GUY","Guyana", col)
col<-gsub("HTI","Haiti", col)
col<-gsub("HND","Honduras", col)
col<-gsub("HUN","Hungary", col)
col<-gsub("ISL","Iceland", col)
# col<-gsub("IND","India", col)
# col<-gsub("IDN","Indonesia", col)
col<-gsub("IRL","Ireland", col)
col<-gsub("IRN","Iran", col)
col<-gsub("IRQ","Iraq", col)
col<-gsub("ISR","Israel", col)
col<-gsub("ITA","Italy", col)
col<-gsub("JAM","Jamaica", col)
# col<-gsub("JOR ","Jordan", col)
col<-gsub("JPN","Japan", col)
# col<-gsub("KEN","Kenya", col)
# col<-gsub("KIR","Kiribati", col)
col<-gsub("KWT","Kuwait", col)
# col<-gsub("KGZ ","Kyrgyz Republic", col)
# col<-gsub("KAZ","Kazakhstan", col)
# col<-gsub("LAO","Laos", col)
# col<-gsub("LVA","Latvia", col)
# col<-gsub("LBR","Liberia", col)
# col<-gsub("LBN","Lebanon", col)
# col<-gsub("LSO","Lesotho", col)
# col<-gsub("LBY","Libya", col)
# col<-gsub("LIE","Liechtenstein", col)
# col<-gsub("LTU","Lithuania", col)
# col<-gsub("LUX","Luxembourg", col)
# col<-gsub("MRT","Mauritania", col)
# col<-gsub("MDG","Madagascar", col)
# col<-gsub("MYS","Malaysia", col)
# col<-gsub("MUS","Mauritius", col)
# col<-gsub("MWI","Malawi", col)
col<-gsub("MEX","Mexico", col)
# col<-gsub("MDA","Moldova", col)
# col<-gsub("MLI","Mali", col)
# col<-gsub("MLT","Malta", col)
# col<-gsub("MCO","Monaco", col)
# col<-gsub("MON","Mongolia", col)
col<-gsub("MAR","Morocco", col)
# col<-gsub("MHL","Marshall Islands", col)
# col<-gsub("MMR","Burma", col)
# col<-gsub("MOZ","Mozambique", col)
# col<-gsub("NAM","Namibia", col)
# col<-gsub("NPL","Nepal", col)
col<-gsub("NZL","New Zealand", col)
# col<-gsub("NIC","Nicaragua", col)
col<-gsub("NGA","Nigeria", col)
# col<-gsub("NER","Niger", col)
col<-gsub("NOR","Norway", col)
col<-gsub("NLD","Netherlands", col)
# col<-gsub("OMN","Oman", col)
# col<-gsub("PAK","Pakistan", col)
# col<-gsub("PLW","Palau", col)
col<-gsub("PAN","Panama", col)
col<-gsub("PRY","Paraguay", col)
col<-gsub("PER","Peru", col)
# col<-gsub("PHL","Philippines", col)
# col<-gsub("PNG","Papua New Guinea", col)
col<-gsub("POL","Poland", col)
col<-gsub("PRT","Portugal", col)
col<-gsub("PRK","North Korea", col)
# col<-gsub("QAT","Qatar", col)
col<-gsub("KOR","South Korea", col)
col<-gsub("ROU","Romania", col)
col<-gsub("ROM","Romania", col)
col<-gsub("RUS","Russia", col)
# col<-gsub("RWA","Rwanda", col)
col<-gsub("ZAF","South Africa", col)
col<-gsub("SLV","El Salvador", col)
col<-gsub("SAU","Saudi Arabia", col)
col<-gsub("SEN","Senegal", col)
# col<-gsub("SYC","Seychelles", col)
# col<-gsub("SLE","Sierra Leone", col)
# col<-gsub("SGP","Singapore", col)
# col<-gsub("KNA","St. Kitts-Nevis", col)
col<-gsub("SVK","Slovakia", col)
# col<-gsub("LCA","St. Lucia", col)
col<-gsub("SVN","Slovenia", col)
# col<-gsub("SMR","San Marino", col)
# col<-gsub("SLB","Solomon Islands", col)
# col<-gsub("SOM","Somalia", col)
col<-gsub("ESP","Spain", col)
# col<-gsub("LKA","Sri Lanka", col)
# col<-gsub("SDN","Sudan", col)
# col<-gsub("SUR","Suriname", col)
# col<-gsub("VCT","St. Vincent and the Grenadines", col)
col<-gsub("SWE","Sweden", col)
col<-gsub("CHE","Switzerland", col)
# col<-gsub("SYR","Syria", col)
# col<-gsub("TJK","Tajikistan", col)
# col<-gsub("TWN","Taiwan", col)
# col<-gsub("TZA","Tanzania", col)
# col<-gsub("THA","Thailand", col)
# col<-gsub("TKM","Turkmenistan", col)
col<-gsub("TGO","Togo", col)
# col<-gsub("TON","Tonga", col)
col<-gsub("TTO","Trinidad-Tobago", col)
col<-gsub("TUN","Tunisia", col)
col<-gsub("TUR","Turkey", col)
# col<-gsub("TUV","Tuvalu", col)
col<-gsub("ARE","UAE", col)
# col<-gsub("UGA","Uganda", col)
col<-gsub("USA","United States", col)
col<-gsub("GBR","United Kingdom", col)
col<-gsub("UKR","Ukraine", col)
col<-gsub("URY","Uruguay", col)
col<-gsub("USR","Soviet Union", col)
# col<-gsub("UZB","Uzbekistan", col)
# col<-gsub("VUT","Vanuatu", col)
# col<-gsub("VEN","Venezuela", col)
# col<-gsub("VNM","Vietnam", col)
# col<-gsub("YEM","Yemen", col)
col<-gsub("YUG","Yugoslavia", col)
# col<-gsub("ZMB","Zambia", col)
# col<-gsub("ZWE","Zimbabwe", col)

return(col)}